#!/usr/bin/env node

/**
 * Скрипт для автоматической генерации реестра компонентов на этапе сборки
 * Сканирует папки с компонентами и создает оптимизированную карту компонентов
 */

const fs = require('fs');
const path = require('path');
const glob = require('glob');

// Конфигурация сканирования
const config = {
    // Папки для сканирования компонентов
    scanDirs: [
        'src/components/cards/**/*Card/*.tsx',
        'src/components/cards/**/*Card/index.tsx',
        'src/components/**/ui/*.tsx'
    ],
    // Выходной файл с зарегистрированными компонентами
    outputFile: 'src/registry/GeneratedComponentMap.ts',
    // Паттерны для поиска метаданных компонентов
    metadataPatterns: {
        cardName: /export\s+.*Card.*=.*\/\/\s*@card\s+([a-zA-Z0-9_]+)/,
        autoRegister: /@AutoRegister\(['"]([^'"]+)['"]\)/,
        displayName: /@displayName\(['"]([^'"]+)['"]\)/,
        category: /@category\(['"]([^'"]+)['"]\)/
    }
};

/**
 * Сканирует файл и извлекает метаданные компонента
 */
function extractComponentMetadata(filePath) {
    const content = fs.readFileSync(filePath, 'utf8');
    const relativePath = path.relative(process.cwd(), filePath);

    const metadata = {
        filePath: relativePath,
        importPath: relativePath.replace(/\.(tsx?)$/, ''),
        cardName: null,
        displayName: null,
        category: null,
        exportedComponents: []
    };

    // Ищем экспорты компонентов
    const exportMatches = content.match(/(export\s+(default\s+)?(?:function|const|class)\s+(\w*Card\w*))/g);
    if (exportMatches) {
        exportMatches.forEach(match => {
            const componentName = match.match(/(\w*Card\w*)/)?.[1];
            if (componentName) {
                metadata.exportedComponents.push(componentName);
            }
        });
    }

    // Ищем метаданные в комментариях
    Object.entries(config.metadataPatterns).forEach(([key, pattern]) => {
        const match = content.match(pattern);
        if (match) {
            metadata[key] = match[1];
        }
    });

    // Если не найден cardName, используем имя файла
    if (!metadata.cardName && metadata.exportedComponents.length > 0) {
        metadata.cardName = metadata.exportedComponents[0];
    }

    return metadata.cardName ? metadata : null;
}

/**
 * Генерирует TypeScript файл с картой компонентов
 */
function generateComponentMapFile(components) {
    const imports = components
        .map(comp =>
            comp.exportedComponents.length > 1
                ? `import { ${comp.exportedComponents.join(', ')} } from '../${comp.importPath}';`
                : `import ${comp.exportedComponents[0]} from '../${comp.importPath}';`
        )
        .join('\n');

    const componentEntries = components
        .map(comp => {
            const componentName = comp.exportedComponents[0];
            return `    '${comp.cardName}': ${componentName}`;
        })
        .join(',\n');

    const metadataEntries = components
        .map(comp => `    '${comp.cardName}': {
        displayName: '${comp.displayName || comp.cardName}',
        category: '${comp.category || 'general'}',
        filePath: '${comp.filePath}',
        generatedAt: '${new Date().toISOString()}'
    }`)
        .join(',\n');

    const fileContent = `/**
 * Auto-generated component registry
 * Generated at: ${new Date().toISOString()}
 *
 * This file is automatically generated by scripts/generateComponentRegistry.js
 * Do not edit manually - your changes will be overwritten
 */

${imports}

import { setBuildTimeComponents } from './BuildTimeRegistry';
import { ComponentType } from './ComponentRegistry';

// Auto-generated component map
export const GENERATED_COMPONENT_MAP: Record<string, ComponentType> = {
${componentEntries}
};

// Auto-generated metadata
export const GENERATED_COMPONENT_METADATA = {
${metadataEntries}
};

// Auto-initialize build-time components
setBuildTimeComponents(GENERATED_COMPONENT_MAP);

console.log(\`[GeneratedComponentMap] Initialized \${Object.keys(GENERATED_COMPONENT_MAP).length} build-time components\`);

export default GENERATED_COMPONENT_MAP;
`;

    return fileContent;
}

/**
 * Главная функция генерации
 */
async function generateRegistry() {
    console.log('🔍 Scanning for UI components...');

    const allComponents = [];

    // Сканируем все директории
    for (const pattern of config.scanDirs) {
        const files = glob.sync(pattern);
        console.log(`📁 Found ${files.length} files in pattern: ${pattern}`);

        for (const file of files) {
            try {
                const metadata = extractComponentMetadata(file);
                if (metadata) {
                    allComponents.push(metadata);
                    console.log(`✅ Registered: ${metadata.cardName} (${metadata.filePath})`);
                }
            } catch (error) {
                console.warn(`⚠️  Error processing ${file}:`, error.message);
            }
        }
    }

    console.log(`\n📝 Generating component registry file...`);
    console.log(`📊 Total components found: ${allComponents.length}`);

    // Генерируем файл
    const outputContent = generateComponentMapFile(allComponents);
    const outputPath = path.resolve(config.outputFile);

    // Создаем директорию если не существует
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // Записываем файл
    fs.writeFileSync(outputPath, outputContent, 'utf8');

    console.log(`✅ Generated component registry: ${outputPath}`);
    console.log(`🎉 Registry generation completed successfully!`);

    return {
        componentsCount: allComponents.length,
        outputPath
    };
}

// Запускаем если файл вызван напрямую
if (require.main === module) {
    generateRegistry().catch(error => {
        console.error('❌ Registry generation failed:', error);
        process.exit(1);
    });
}

module.exports = {
    generateRegistry,
    extractComponentMetadata,
    config
};